#!/bin/bash

STASH_NAME=$(git stash list | grep "pre-commit-stash" | awk -F: '{print $1}')
if [ -n "$STASH_NAME" ]; then
    echo "Unstashing unstaged changes"
    git stash pop "$STASH_NAME"
else
    echo "No changes to unstash"
fi
